### PR TITLE
Added DotMatchesLineSeparators and updated Quick version

### PR DESCRIPTION
**Pull request by ninjaprawn**
I have noticed myself quite a lot using this Regex framework for looking for paragraphs of text. One feature that I found was missing was dots match newlines. I decided to add that feature as an option for this framework.

I also updated the Quick and Nimble versions to the latest version.

### CODE REVIEW

**Comment by ninjaprawn** [comment]
Looks like Travis was having some problems ("GitHub API request failed: Maximum number of login attempts exceeded. Please try again later.")

**Comment by sharplet** [comment]
Thanks for the PR @ninjaprawn and sorry for the long wait! I think this is a good change. I've kicked off the travis build again to see if there's any issues.

There's some indentation that's a little off: would you mind making sure everything is consistently indented using 2 spaces?

Also, would you be comfortable rebasing and squashing your changes? I can take care of it if not.

**Comment by ninjaprawn** [comment]
@sharplet No problem!

Regarding your statement about rebasing: I have no clue how to do so. I guess some more reading on git is required, but do you mind if you do that?

**Comment by sharplet** [comment]
@ninjaprawn I went ahead and did those little cleanups. If you're interested in reading up on rewriting history, I think [this](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history) is a pretty good writeup. Thanks again!

**Pull request closed without merging**
