### PR TITLE
Modernize to work with Swift 4.2

### PR DESCRIPTION
**Pull request by tonyarnold**
:wave: @sharplet 

No worries if you don't want this monster of a PR, but I thought I'd offer it back all the same. 

This has been tested to work with SPM 4.2 and 5.0, as well as Xcode 10.1 and 10.2 beta. 

Sorry for removing Quick & Nimble, but they were getting in the way of SPM working.

### CODE REVIEW

**Comment by iby** [comment]
@tonyarnold I feel we desperately need this PR! What's up with Quick & Nimble? They are SPM compatible, pretty sure I've used them all together a few weeks ago… 🤔

**Comment by sharplet** [comment]
Sorry for the delay, but thanks a bunch @tonyarnold! I’ve just merged your changes as part of https://github.com/sharplet/Regex/commit/64385f3a4c19db62cbde3925d27ead7b7c99bb83. I’ll be putting out 2.0 shortly.

**Comment by tonyarnold** [comment]
I’d have to check when I’m home (I’m away on work for a few days) - I can’t remember exactly what the problem was, but I couldn’t resolve it easily. I’ll try to have a look tonight 👍🏻

**Comment by tonyarnold** [comment]
Oh not a worry @sharplet - I know how it goes. Never apologise for OSS 😉

**Pull request merged**
