### PR TITLE
Moved tests into 'RegexTests' folder as required by Swift PM

### PR DESCRIPTION
**Pull request by andrew804**
Fixes issue #46

### CODE REVIEW

**Review by sharplet — CHANGES_REQUESTED** [review]
Thanks! Could you update all the test targets to use the new location for the test Info.plist? https://travis-ci.org/sharplet/Regex/jobs/182034761#L437

**Comment by sharplet** [comment]
In the latest build failure, it looks like the test files have been added to the `Regex` module instead of `RegexTests`.

**Comment by andrew804** [comment]
So they have, sorry about that!

**Comment by andrew804** [comment]
When are you planing to merge this fix?

**Comment by sharplet** [comment]
Thanks @andrew804!

**Comment by andrew804** [comment]
No problem!

**Pull request merged**
